### ISSUE TITLE
how to use zonetool

### ISSUE THREAD

**Issue by S1ncer3ly** [DoktorSAS/PlutoniumIW5Mapvote#1]
its not opening and maybe im doing anything wrong please help im new trying to revive this in India if you can help thankyou 

![image](https://user-images.githubusercontent.com/70603773/170835341-78ca73ea-07f9-43c1-b8a3-3d2300ccecb7.png)

and aslo i dont know how to use it please help 
i unpacked this with the files given at the https://forum.plutonium.pw/topic/19301/release-modern-warfare-iii-mapvote?_=1653752417739

**Comment by DoktorSAS** [comment]
Its not an issue with the mapvote.

You can find in the readme.md/.txt a guide on how to install it. For info about the zonetool go in the right github page https://github.com/ZoneTool/zonetool
